[build]
  command = "cd docs && bundle install && bundle exec jekyll build -d ../_site"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

